#!/bin/sh
# system one time tasks

# /bin/bash -- if you want to debug, or, could just as well use
#    init=/bin/bash in kernel command line or in initramfs init

PATH=/sbin:/bin:/usr/sbin:/usr/bin

RUNLEVEL=S /sbin/rc sysinit
RUNLEVEL=S /sbin/rc boot

# Do not start services besides tty's if we're running single-user.
if [ ! -n "$(grep single /proc/cmdline)" ]
then
   # taken the below from /etc/rc.multi
   # /sbin/asynx_spawn /etc/rc.X
   /sbin/rc default
fi

# the best guide on process management
# http://mywiki.wooledge.org/ProcessManagement
declare -a kids=()

# below happens when this shell script is exiting
#   gets called on INT, HUP and TERM to the shell script
trap 'echo "trap function called"; kill "${kids[@]}";' EXIT

for i in {1..5}
do
   /sbin/respawn -- /etc/rc.tty "${i}" &
   kids+=($!)
done

# By default, wait waits for all of your shell's kids to exit. 
wait

exit 0
# vim:filetype=sh tabstop=3 shiftwidth=3 expandtab
